Repository sudhanshutiwari264/Making-class-in-different-Programming-languages-, pull requests merged in 2020-10, with the labels that each got.

#7 Class_in_cpp.cpp
  Class_In_Cpp.cpp
Labels: classes and objects, enhancement, hacktoberfest-accepted, ‘hacktoberfest-accepted’

#5 Create class.js
  Vehicle .dart
  Vehicle.kt
  class.js
Labels: classes and objects, good first issue, hacktoberfest-accepted

#11 Add class in golang
  ClassInGolang.go
Labels: classes and objects, hacktoberfest-accepted, ‘hacktoberfest-accepted’

#12 Adding ClassInPHP.php
  ClassInPHP.php
Labels: classes and objects, good first issue, hacktoberfest-accepted, ‘hacktoberfest-accepted’

#16 Added JSDocs, export
  vehicle.js
Labels: classes and objects, good first issue, hacktoberfest-accepted, ‘hacktoberfest-accepted’

#15 Vehicle.groovy
  Vehicle.groovy
Labels: classes and objects, good first issue, hacktoberfest-accepted, ‘hacktoberfest-accepted’

#20 added typescript
  vehicle.ts
Labels: classes and objects, hacktoberfest-accepted, ‘hacktoberfest-accepted’

#24 Added Maintainer !
  README.md
Labels: documentation

#26 add-class-in-cpp
  Class-In-CPP.cpp
Labels: classes and objects, good first issue, hacktoberfest-accepted, ‘hacktoberfest-accepted’

#17 Added C#
  ClassInC#.cs
Labels: hacktoberfest-accepted, help wanted, ‘hacktoberfest-accepted’

#14 Create inheritance code.cpp
  inheritance code.cpp
Labels: classes and objects, good first issue, hacktoberfest-accepted, ‘hacktoberfest-accepted’

#28 Create ClassInSwift.swift
  Vehicle Class/ClassInSwift.swift
Labels: classes and objects, good first issue, hacktoberfest-accepted, ‘hacktoberfest-accepted’

#35 Add files via upload
  Other Examples/Python examples/Hierarchical Inheritance in python.py
Labels: classes and objects, good first issue, hacktoberfest-accepted, ‘hacktoberfest-accepted’

#37 Added Multiple Inheritance Class in Python
  Other Examples/Python examples/MultipleInheritanceInPython.py
Labels: classes and objects, hacktoberfest-accepted, ‘hacktoberfest-accepted’
